accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.models import Student
from . import views


app_name = "accounts"

urlpatterns = [
    path("profile/", views.profile, name="profile"),
    path("register/", views.register, name="register"),
    path("my_registrations/", views.my_registrations, name="my_registrations"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout",
        auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
    path("profile/<int:pk>/", views.profile, name="profile"),
]

courseapp/urls.py
from django.urls import path, include
from courseapp import views


app_name = "courseapp"

# URL Configurations
urlpatterns = [
    path("", views.home, name="home"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("registrations", views.registrations, name="registrations"),
    path("modules", views.module_list, name="module_list"),
    path("module/<str:code>/", views.module_detail, name="module_detail"),
    path("course/<int:pk>/", views.course_detail, name="course_detail"),
    path("register/<str:code>/", views.register_view, name="register"),
    path("unregister/<str:code>/", views.unregister_view, name="unregister"),
]

registrationapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from courseapp.views import ApiRoot,CoursesList,ModulesList,RegistrationsList,UsersList,StudentsList
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("courseapp.urls")),
    path("accounts/", include("accounts.urls")),
path(
        "password_reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.CustomPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.CustomPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path('api/',ApiRoot.as_view(),name=ApiRoot.name),
    path('api/students/', StudentsList.as_view(), name=StudentsList.name),
    path('api/users/', UsersList.as_view(), name=UsersList.name),
    path('api/courses/', CoursesList.as_view(), name=CoursesList.name),
    path('api/modules/', ModulesList.as_view(), name=ModulesList.name),
    path('api/registration/', RegistrationsList.as_view(), name=RegistrationsList.name),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User, Group


class Student(models.Model):
    address = models.CharField(max_length=100)
    town = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    dob = models.DateField(null=True, blank=True)
    course = models.ForeignKey(Group, on_delete=models.CASCADE, blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(default="default.png", upload_to="profile_photos")

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def student_registrations(self):
        return [registration.module for registration in self.registrations.all()]

accounts/forms.py
from django import forms
from django.contrib.auth.models import User,Group
from django.contrib.auth.forms import UserCreationForm
from accounts.models import Student


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label = 'Email address', help_text = 'Your email address.')
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
     email = forms.EmailField()
     
     class Meta:
          model = User
          fields = ['first_name', 'last_name', 'email']

   
class ProfileUpdateForm(forms.ModelForm):
    photo = forms.ImageField(required=False)
    course=forms.ModelChoiceField(queryset=Group.objects.all(),empty_label="Choose a course")
     
    class Meta:
        model = Student
        fields = ['photo', 'course']
          

accounts/views.py
from django.urls import reverse
from django.shortcuts import render, redirect

from registrationapp.decorators import login_required_with_message
from .forms import UserUpdateForm, UserRegisterForm
from django.contrib import messages
from .forms import ProfileUpdateForm, UserUpdateForm
from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView


@login_required_with_message(message="You need to log in to access this page.")
def profile(request):
    student = request.user.student

    if request.method == "POST":
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=student)
        u_form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, "Your profile has been updated!")
            return redirect("accounts:profile")
    else:
        p_form = ProfileUpdateForm(instance=student)
        u_form = UserUpdateForm(instance=request.user)

    context = {"student": student, "p_form": p_form, "u_form": u_form}

    # Disable the course field if user already has a course assigned
    if student.course:
        p_form.fields["course"].widget.attrs["disabled"] = True

    return render(request, "accounts/profile.html", context)


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, f"Your account has been created! Now you can login!"
            )
            return redirect("accounts:login")
        else:
            messages.warning(request, f"Unable to create account!")
        return redirect("courseapp:home")
    else:
        form = UserRegisterForm()
        return render(request, "accounts/register.html", {"form": form})


@login_required_with_message(message="You need to log in to access this page.")
def my_registrations(request):
    # import pdb

    # pdb.set_trace()
    context = {"registered_modules": request.user.student.student_registrations}
    return render(request, "accounts/my_registrations.html", context)


class CustomPasswordResetView(PasswordResetView):
    email_template_name = "password_reset_email.html"
    subject_template_name = "mail_subject.txt"
    template_name = "password_reset_form.html"

    def get_success_url(self):
        return reverse("password_reset_done")


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = "password_reset_done.html"


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "password_reset_confirm.html"
    def get_success_url(self):
        return reverse("login")


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "password_reset_complete.html"

accounts/templates/accounts/login.html
{% extends "courseapp/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<br>
<div class="container">
    <div class="" data-aos="fade-up"
    data-aos-duration="3000">
    
<div  class="card mx-auto" style="width: 700px;">
    <div class="card-body">
<div class="row">
    <div class="col-md-12">
        <br>
        <h3 class="text-info text-center font-weight-bold">Login</h3>
        <br>
        <form method="post">
            {% csrf_token %}

            {{ form|crispy }}

            <button class="btn btn-success" type="submit">Login</button>
            <a href="{% url 'password_reset' %}" class="btn btn-outline-danger"> Forgot password</a>

        </form>
        <br>
    </div>
    </div>

        
    </div>

</div>


{% endblock content %}

accounts/templates/accounts/logout.html
{% extends "courseapp/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="content-section">
        <h1 class="text-success">You have logged out!</h1>
    </div>
   
</div>



{% endblock content %}

accounts/templates/accounts/my_registrations.html
{% extends "courseapp/base.html" %} {% block content %}

<div class="card">
  <div class="card-body">
    <h4 class="card-title">My registrations</h4>
    <ul class="list-group">
      {% for module in registered_modules %}
      <li class="list-group-item">
        <a href="{% url 'courseapp:module_detail' module.code %}">{{ module.name }}</a>
        
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "courseapp/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="content-section" data-aos="fade-up"
    data-aos-duration="3000">
    <legend class="border-bottom mb-4 text-success " > Student Profile Details</legend>
    <div class="media" data-aos="fade-right"
    data-aos-offset="300"
    data-aos-easing="ease-in-sine">

    <p><img class="rounded-circle account-img" src="{{user.student.photo.url}}"></p>
    
    <div class="media-body">
    
    <h2 class="account-heading text-info" data-aos="fade-up"
    data-aos-duration="3000">{{user.first_name}}  {{user.last_name}}</h2>
    <h6 class="text-secondary" data-aos="fade-up"
    data-aos-duration="3000">Course: {{user.student.course}}</h6>
    <h6 class="text-secondary" data-aos="fade-up"
    data-aos-duration="3000">Email: {{user.email}}</h6>
    
    
    
    </div>
    
    </div>
    <br>
    <form method="POST" enctype="multipart/form-data">

{% csrf_token %}

<fieldset class="form-group">

{{ u_form|crispy}}
{{ p_form|crispy}}

</fieldset>

<div class="form-group">

<button class="btn btn-outline-info" type="submit" data-aos="fade-up"
data-aos-duration="2000">Update</button>

</div>

</form>

    </div>
</div>
<br><br>

{% endblock content %}


{% block sidebar %}

<div class="col-md-4">
    <div class="content-section">
        <h4>Links </h4>
        <ul class="list-group">                
            <li class="list-group-item list-group-item-light">
                <a class="mr-2" href="{% url 'accounts:my_registrations' %}">
                    My registrations
                </a>
            </li>
        </ul>
    </div>

</div>


{% endblock %}

accounts/templates/accounts/register.html
{% extends "courseapp/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <br>
    <div class="card mx-auto" style="width: 700px;">
        <div class="row" >
        <div class="col-md-12">
            <div class="card-body" data-aos="fade-up"
            data-aos-duration="3000">
                <br>
                <h3 class="text-info text-center font-weight-bold">REGISTER</h3>
                <br>

                <form method="post">
                    {% csrf_token %}

                    {{ form|crispy }}


                    <div style="padding-bottom: 10px;">
                        <button class="btn btn-outline-info" type="submit">Register</button>
                    </div>

                </form>

            </div>
        </div>
    </div>
    </div>
    <br>

</div>


{% endblock content %}