accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.models import Student
from . import views


app_name = "accounts"

urlpatterns = [
    path("profile/", views.profile, name="profile"),
    path("register/", views.register, name="register"),
    path("my_registrations/", views.my_registrations, name="my_registrations"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout",
        auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
    path("profile/<int:pk>/", views.profile, name="profile"),
]

courseapp/urls.py
from django.urls import path, include
from courseapp import views


app_name = "courseapp"

# URL Configurations
urlpatterns = [
    path("", views.home, name="home"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("registrations", views.registrations, name="registrations"),
    path("modules", views.module_list, name="module_list"),
    path("module/<str:code>/", views.module_detail, name="module_detail"),
    path("course/<int:pk>/", views.course_detail, name="course_detail"),
    path("register/<str:code>/", views.register_view, name="register"),
    path("unregister/<str:code>/", views.unregister_view, name="unregister"),
]

registrationapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from courseapp.views import ApiRoot,CoursesList,ModulesList,RegistrationsList,UsersList,StudentsList
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("courseapp.urls")),
    path("accounts/", include("accounts.urls")),
path(
        "password_reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.CustomPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.CustomPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path('api/',ApiRoot.as_view(),name=ApiRoot.name),
    path('api/students/', StudentsList.as_view(), name=StudentsList.name),
    path('api/users/', UsersList.as_view(), name=UsersList.name),
    path('api/courses/', CoursesList.as_view(), name=CoursesList.name),
    path('api/modules/', ModulesList.as_view(), name=ModulesList.name),
    path('api/registration/', RegistrationsList.as_view(), name=RegistrationsList.name),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

courseapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User, Group
from accounts.models import Student


class Module(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100)
    credit = models.IntegerField()
    description = models.TextField()
    category = models.CharField(max_length=100)
    availability = models.BooleanField(default=True)
    courses = models.ManyToManyField(Group, related_name="modules")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("courseapp:module-list", kwargs={"pk": self.pk})


class Registration(models.Model):
    student = models.ForeignKey(
        Student, on_delete=models.CASCADE, related_name="registrations"
    )
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    registration_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Student ID: {self.student.user.username} registered for: {self.module.name}"

    class Meta:
        unique_together = ["student", "module"]

courseapp/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label="Your Name", max_length=100)
    email = forms.EmailField(label="Your Email")
    subject = forms.CharField(label="Subject", max_length=200)
    message = forms.CharField(label="Your Message", widget=forms.Textarea)

courseapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from registrationapp.decorators import login_required_with_message
from .models import Module, Registration
from django.contrib.auth.models import Group
from django.contrib import messages
from django.core.paginator import Paginator
from courseapp.serializers import CourseSerializer,ModuleSerializer,UserSerializer,StudentSerializer,RegistrationSerializer
from rest_framework import serializers
from rest_framework.response import Response
from rest_framework import  generics, status
from accounts.models import Student,User,Group
from .forms import ContactForm
from django.core.mail import send_mail


def home(request):
    return render(request, "courseapp/home.html", {"title": "Home page"})


def about(request):
    return render(request, "courseapp/about.html", {"title": "About US"})







def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            
            recipient_email = 'david.okose@hotmail.com'  # Replace with recipient's email
            
            send_mail(
                subject,
                f"From: {name} <{email}>\n\n{message}",
                email,  # Sender's email
                [recipient_email],  # Recipient's email
                fail_silently=False,
            )
            
            # Add a success message
            messages.success(request, 'Your message was successfully sent!')
            
            return redirect('courseapp:contact')  # Redirect back to the contact page
    else:
        form = ContactForm()

    return render(request, "courseapp/contact.html", {"title": "Contact Us", "form": form})


















@login_required_with_message(message="You need to log in to access this page.")
def module_list(request):
    modules = Module.objects.all()
    return render(request, "courseapp/module_list.html", {"modules": modules})


def module_detail(request, code):
    module = get_object_or_404(Module, code=code)
    registered_students = Registration.objects.filter(module=module).select_related('student__user')
    module.registered_students = registered_students
    # Check if the user is registered for this module
    registered = False
    if request.user.is_authenticated:
        registered = Registration.objects.filter(
            student=request.user.student, module=module
        ).exists()
    context = {
        'module': module,
        "registered": registered, 
        'registered_students': registered_students 
        }
    return render(request, 'courseapp/module_detail.html', context)

@login_required_with_message(message="You need to log in to access this page.")
def registrations(request):
    modules = Module.objects.all()
    for module in modules:
        registered_students = Registration.objects.filter(module=module).select_related('student__user')
        module.registered_students = registered_students

        # Check if the user is registered for this module and attach the result to the module object
        module.is_registered = False
        if request.user.is_authenticated:
            module.is_registered = Registration.objects.filter(
                student=request.user.student, module=module
            ).exists()

    paginator = Paginator(modules, 1)  # Display 1 module per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
    }

    if request.method == 'POST':
        module_code = request.POST.get('module_code')
        try:
            module = Module.objects.get(code=module_code)
        except Module.DoesNotExist:
            return redirect('courseapp:registrations')  # Redirect to the same page if the module does not exist

        if request.user.is_authenticated:
            if 'register' in request.POST:
                Registration.objects.create(student=request.user.student, module=module)
            elif 'unregister' in request.POST:
                Registration.objects.filter(student=request.user.student, module=module).delete()

        return redirect('courseapp:registrations')  # Redirect to the same page after registration/unregistration

    return render(request, "courseapp/registrations.html", context)

@login_required_with_message(message="You need to log in to access this page.")
def course_detail(request, pk):
    course = get_object_or_404(Group, pk=pk)
    modules = course.modules.all()
    context = {"course": course, "modules": modules}
    return render(request, "courseapp/course_detail.html", context)



@login_required_with_message(message="You need to log in to access this page.")
def register_view(request, code):
    module = Module.objects.get(code=code)
    student = request.user.student
    registration, created = Registration.objects.get_or_create(
        student=student, module=module
    )
    if created:
        messages.success(request, f"You have registered for {module.name}")
        return redirect(
            reverse("courseapp:module_detail", args=[code])
        )  # Redirect to the desired page after registration
    else:
        messages.warning(request, "Something went wrong")


@login_required_with_message(message="You need to log in to access this page.")
def unregister_view(request, code):
    module = Module.objects.get(code=code)
    registration = Registration.objects.filter(
        student=request.user.student, module=module
    )
    if registration.exists():
        registration.delete()
        messages.warning(request, "Unregister succesful")
        return redirect(reverse("courseapp:module_detail", args=[code]))
    else:
        messages.warning(request, "Unregister failed")



      
class ApiRoot(generics.GenericAPIView):
    """
    API homepage
    """

    name = 'api-root'
    def get(self, request, *args, **kwargs):
        return Response({
            'users': request.build_absolute_uri(reverse(UsersList.name)),
            'students': request.build_absolute_uri(reverse(StudentsList.name)),
            'modules': request.build_absolute_uri(reverse(ModulesList.name)),
            'courses': request.build_absolute_uri(reverse(CoursesList.name)),
            'registation': request.build_absolute_uri(reverse(RegistrationsList.name))
            })

class StudentsList(generics.ListCreateAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer
    name = "student-list"
    
class UsersList(generics.ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    name = "user-list"

class CoursesList(generics.ListCreateAPIView):
    queryset = Group.objects.all()
    serializer_class = CourseSerializer
    name = "groups-list"

class ModulesList(generics.ListCreateAPIView):
    queryset = Module.objects.all()
    serializer_class = ModuleSerializer
    name = "modules-list"

class RegistrationsList(generics.ListCreateAPIView):
    queryset = Registration.objects.all()
    serializer_class = RegistrationSerializer
    name = "registration-list"

courseapp/templates/courseapp/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.0.0/font/bootstrap-icons.css" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

  <!-- AOS CSS -->
  <link href="https://cdn.jsdelivr.net/npm/aos@next/dist/aos.css" rel="stylesheet">
  <!-- Favicons -->
  <link href="{%static 'img/favicon.png' %}" rel="icon">
  <link href=" {%static 'img/apple-touch-icon.png '%} " rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <!--  -->
  
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  
  
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <title>Happy University - {{title}}</title>
</head>

<body>
  <header class="site-header ">
    <nav class="navbar navbar-expand-md navbar-dark bg-info text-white fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'courseapp:home' %}">Happy University</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto ">
            <a class="nav-item nav-link text-white " href="{% url 'courseapp:home' %}">Home</a>
            <a class="nav-item nav-link text-white" href="{% url 'courseapp:about' %}">About</a>
            <a class="nav-item nav-link text-white" href="{% url 'courseapp:contact' %}">Contact</a>
            <a class="nav-item nav-link text-white" href="{% url 'courseapp:module_list' %}">Modules</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav text-white">

            {% if user.is_authenticated %}
            <a class="nav-item nav-link text-white" href="{% url 'courseapp:registrations' %}">Registrations</a>
            <a class="nav-item nav-link text-white" href="{% url 'accounts:profile' %}">Profile</a>
            <a class="nav-item nav-link text-white" href="{% url 'accounts:logout' %}">Logout</a>


            {% else %}

            <a class="nav-item nav-link text-white" href="{% url 'accounts:login' %}">Login</a>

            <a class="nav-item nav-link text-white" href="{% url 'accounts:register' %}">Register</a>

            {% endif %}

          </div>
        </div>
      </div>
    </nav>
  </header>
  {% if messages %}
  {% for message in messages %}
  <div class="container">
    <div class="alert alert-{{message.tags}}">{{ message }}</div>
  </div>
  
  <div class="">
    <div class="">


      {% endfor %}
      {% endif %}

      {% block content %}
      {% endblock %}
    </div>
    

  </div>




  <!-- ======= Footer ======= -->
  <footer class="footer bg-info">
    <div class="container">
      <p class='text-white '>&copy; 2023 Happy Universe</p>
    </div>
  </footer>

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>




  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>


  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
  
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <!-- AOS JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/aos@next/dist/aos.js"></script>


  <!-- Template Main JS File -->
  <script src=" {%static 'js/main.js'%} "></script>


</body>

</html>

courseapp/templates/courseapp/home.html
{% extends "courseapp/base.html" %}
{% load static %}

{% block content %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex justify-content-center align-items-center">
  <div class="container position-relative" data-aos="zoom-in" data-aos-delay="100">
    <h1>Unlocking Potential, Inspiring Minds:</h1>
    <h2> Where Tomorrow's Leaders Thrive</h2>
    <a href="" class="btn-get-started">Get Started</a>
  </div>
</section><!-- End Hero -->

<main id="main">

  <!-- ======= About Section ======= -->
  <section id="about" class="about">
    <div class="container " data-aos="fade-up">

      <div class="row">
        <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
          <img src="{% static 'img/about.jpg' %}" class="img-fluid" alt="">
        </div>
        <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
          <h3>Excepteur sint sunt in culpa qui officia deserunt mollit anim id est laborum.</h3>
          <p class="fst-italic">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
            ea commodo consequat.
          </p>
          <ul>
            <li><i class="bi bi-check-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
            <li><i class="bi bi-check-circle"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
            <li><i class="bi bi-check-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
              irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.
            </li>
          </ul>
          <p>
            Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
          </p>

        </div>
      </div>

    </div>
  </section><!-- End About Section -->

  <!-- ======= Counts Section ======= -->
  <section id="counts" class="counts section-bg">
    <div class="container">

      <div class="row counters">

        <div class="col-lg-3 col-6 text-center">
          <span data-purecounter-start="0" data-purecounter-end="1232" data-purecounter-duration="1"
            class="purecounter"></span>
          <p>Students</p>
        </div>

        <div class="col-lg-3 col-6 text-center">
          <span data-purecounter-start="0" data-purecounter-end="64" data-purecounter-duration="1"
            class="purecounter"></span>
          <p>Courses</p>
        </div>

        <div class="col-lg-3 col-6 text-center">
          <span data-purecounter-start="0" data-purecounter-end="42" data-purecounter-duration="1"
            class="purecounter"></span>
          <p>Events</p>
        </div>

        <div class="col-lg-3 col-6 text-center">
          <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1"
            class="purecounter"></span>
          <p>Trainers</p>
        </div>

      </div>

    </div>
  </section><!-- End Counts Section -->

  <!-- ======= Why Us Section ======= -->
  <section id="why-us" class="why-us bg-info">
    <div class="container" data-aos="fade-up">

      <div class="row">
        <div class="col-lg-4 d-flex align-items-stretch">
          <div class="content bg-dark">
            <h3 class="text-white">Why Choose Us?</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua. Duis aute irure dolor in reprehenderit
              Asperiores dolores sed et. Tenetur quia eos. Autem tempore quibusdam vel necessitatibus optio ad corporis.
            </p>
            <div class="text-center">
              <a href="{% url 'courseapp:about' %}" class="more-btn">Learn More <i class="bx bx-chevron-right"></i></a>
            </div>
          </div>
        </div>
        <div class="col-lg-8 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
          <div class="icon-boxes d-flex flex-column justify-content-center">
            <div class="row">
              <div class="col-xl-4 d-flex align-items-stretch">
                <div class="icon-box mt-4 mt-xl-0">
                  <i class="bx bx-receipt"></i>
                  <h4>Corporis voluptates sit</h4>
                  <p>Consequuntur sunt aut quasi enim aliquam quae harum pariatur laboris nisi ut aliquip</p>
                </div>
              </div>
              <div class="col-xl-4 d-flex align-items-stretch">
                <div class="icon-box mt-4 mt-xl-0">
                  <i class="bx bx-cube-alt"></i>
                  <h4>Ullamco laboris ladore pan</h4>
                  <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt</p>
                </div>
              </div>
              <div class="col-xl-4 d-flex align-items-stretch">
                <div class="icon-box mt-4 mt-xl-0">
                  <i class="bx bx-images"></i>
                  <h4>Labore consequatur</h4>
                  <p>Aut suscipit aut cum nemo deleniti aut omnis. Doloribus ut maiores omnis facere</p>
                </div>
              </div>
            </div>
          </div><!-- End .content-->
        </div>
      </div>

    </div>
  </section><!-- End Why Us Section -->


  <!-- ======= Popular Courses Section ======= -->
  <section id="popular-courses" class="courses">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>Courses</h2>
        <p>Popular Courses</p>
      </div>

      <div class="row" data-aos="zoom-in" data-aos-delay="100">



        {% for course in courses %}
        <div class="col-lg-3 col-md-6 d-flex align-items-stretch mt-4 mt-md-0 mb-4">
          <div class="card" style="width: 18rem;">
          
            <div class="card-body">
              <h5 class="card-title">{{course.name}}</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
                content.</p>
              <a href="{% url 'courseapp:course_detail' course.id %}" class="btn btn-success">Learn more</a>
            </div>
          </div>
        </div>

        {% endfor %}



      </div> <!-- End Course Item-->

    </div>

    </div>



  </section><!-- End Popular Courses Section -->

  <!-- ======= Trainers Section ======= -->
  <section id="trainers" class="trainers">
    <div class="container" data-aos="fade-up">

      <div class="row" data-aos="zoom-in" data-aos-delay="100">
        <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
          <div class="member">
            <img src=" {% static 'img/trainers/trainer-1.jpg' %}" class="img-fluid" alt="">
            <div class="member-content">
              <h4>Walter White</h4>
              <span>Web Development</span>
              <p>
                Magni qui quod omnis unde et eos fuga et exercitationem. Odio veritatis perspiciatis quaerat qui aut aut
                aut
              </p>
              <div class="social">
                <a href=""><i class="bi bi-twitter"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
          <div class="member">
            <img src="{% static 'img/trainers/trainer-2.jpg' %}" class="img-fluid" alt="">
            <div class="member-content">
              <h4>Sarah Jhinson</h4>
              <span>Marketing</span>
              <p>
                Repellat fugiat adipisci nemo illum nesciunt voluptas repellendus. In architecto rerum rerum temporibus
              </p>
              <div class="social">
                <a href=""><i class="bi bi-twitter"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
          <div class="member">
            <img src=" {% static 'img/trainers/trainer-3.jpg'%} " class="img-fluid" alt="">
            <div class="member-content">
              <h4>William Anderson</h4>
              <span>Content</span>
              <p>
                Voluptas necessitatibus occaecati quia. Earum totam consequuntur qui porro et laborum toro des clara
              </p>
              <div class="social">
                <a href=""><i class="bi bi-twitter"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
  </section><!-- End Trainers Section -->

</main><!-- End #main -->



{% endblock content %}

courseapp/templates/courseapp/module_detail.html
{% extends "courseapp/base.html" %}

{% block content %}

<div class="container">
  <br>
  <div class="card">
  <div class="card-body">
    <h3 class="card-header text-success">{{ module.name }} Details</h3>
    <ul class="list-group">
      <li class="list-group-item">Course Code: {{ module.code }}</li>
      <li class="list-group-item">Course Credit: {{ module.credit }}</li>
    </ul> <br>
    {% if user.is_authenticated %}
      {% if registered %}
        <form method="post" action="{% url 'courseapp:unregister' module.code %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-outline-danger">Unregister</button>
        </form>
      {% else %}
        <form method="post" action="{% url 'courseapp:register' module.code %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-outline-success">Register</button>
        </form>
      {% endif %}
    {% endif %}
  </div>
  
  <div class="">
    <h5 class="text-info card-header">Registered Students</h5>
     {% if module.registered_students.exists %}
      {% for registration in module.registered_students %}
          <ul class="list-group">
              <li class="list-group-item list-group-item-light" data-aos="fade-in">
                  <img class="rounded-circle article-img" src="{{ registration.student.photo.url }}" >
                  <span class="article-content text-muted">{{ registration.student.user.first_name }} {{ registration.student.user.last_name }}</span>
              </li>
          </ul>
     
      {% endfor %}
  {% else %}
  <div class="card-body">
    <p>No student registered.</p>
  </div>
      
  {% endif %}
  </div>
  
 
      </div>
      
  <br>
</div>
  
 
   
    
    
    
   


{% endblock %}

courseapp/templates/courseapp/module_list.html
{% extends "courseapp/base.html" %}

{% load static}
{% block content %}

<main id="main" data-aos="fade-in">

  <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs">
    <div class="container">
      <h2 class="text-white"> Available Courses</h2>
    </div>
  </div><!-- End Breadcrumbs -->

  <!-- ======= Courses Section ======= -->
  <section id="courses" class="courses">
    <div class="container" data-aos="fade-up">

      <div class="row" data-aos="zoom-in" data-aos-delay="100">


        {% for course in courses %}
        <div class="col-lg-3 col-md-6 d-flex align-items-stretch mt-4 mt-md-0 mb-4">
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{ course.name }}</h5>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="{% url 'courseapp:course_detail' course.id %}" class="btn btn-success">Learn more</a>
            </div>
          </div>
        </div>

        {% endfor %}



      </div> <!-- End Course Item-->


    </div>
  </section><!-- End Courses Section -->

</main><!-- End #main -->

{% endblock content %}

courseapp/templates/courseapp/register.html
{% extends "courseapp/base.html" %}

{% block content %}

<h2>Unregister from {{ module.name }}</h2>
<form method="post" action="{% url 'courseapp:unregister' module.code %}">
  {% csrf_token %}
  <p>Are you sure you want to unregister from this module?</p>
  <button type="submit">Unregister</button>
</form>



{% endblock content %}